AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReactS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

Outputs:
  ReactS3BucketName:
    Value: !Ref ReactS3Bucket
